services:
  db:
    image: postgres:15
    container_name: db_app
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis_app
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    command: [ "/frameshelf/docker/app.sh" ]
    ports:
      - 9996:8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery:
    build:
      context: .
    env_file:
      - .env
    container_name: celery_app
    command: [ "/frameshelf/docker/celery.sh"]
    depends_on:
      redis:
        condition: service_healthy

volumes:
  db_data:
  redis_data: